=== mfecteau/Mark---Repo/Purdue/1/xmlschema/icd/enmapper.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="EnumMapper">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="EnumType" nillable="true" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="EnumPair" nillable="true" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="systemName" type="xs:string"/>
									<xs:attribute name="userLabel" type="xs:string"/>
									<xs:attribute name="hidden" type="xs:boolean"/>
									<xs:attribute name="customValue" type="xs:boolean"/>
									<xs:attribute name="preserve" type="xs:boolean"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="enumName" type="Enumerations"/>
						<xs:attribute name="enumLabel" type="xs:string"/>
						<xs:attribute name="toolTip" type="xs:string"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="BaseEnumerations">
		<xs:restriction base="xs:token">
			<xs:enumeration value="AcceptsHealthyVolunteersTypes"/>
			<xs:enumeration value="AllocationTypes"/>
			<xs:enumeration value="AlphaTailTypes"/>
			<xs:enumeration value="BlindingTypes"/>
			<xs:enumeration value="CentralFacilityTypes"/>
			<xs:enumeration value="CodedPhaseTypes"/>
			<xs:enumeration value="ConfigurationTypes"/>
			<xs:enumeration value="ContactRoleTypes"/>
			<xs:enumeration value="ControlTypes"/>
			<xs:enumeration value="CTMaterialRoleTypes"/>
			<xs:enumeration value="CTMaterialTypes"/>
			<xs:enumeration value="CurrencyTypes"/>
			<xs:enumeration value="EntranceCriterionClassifierTypes"/>
			<xs:enumeration value="EntranceCriterionTypes"/>
			<xs:enumeration value="FormulationTypes"/>
			<xs:enumeration value="GenderTypes"/>
			<xs:enumeration value="InvestigationTypes"/>
			<xs:enumeration value="LocalFacilityTypes"/>
			<xs:enumeration value="MultiCenteredTypes"/>
			<xs:enumeration value="ObjectiveTypes"/>
			<xs:enumeration value="OrganizationTypes"/>
			<xs:enumeration value="OutcomeTypes"/>
			<xs:enumeration value="OverallStudyOutcomeTypes"/>
			<xs:enumeration value="PurposeTypes"/>
			<xs:enumeration value="RouteOfAdminTypes"/>
			<xs:enumeration value="ScheduleItemTypes"/>
			<xs:enumeration value="StudyPurposeTypes"/>
			<xs:enumeration value="TimeUnit"/>
			<xs:enumeration value="RestrictedTimeUnit"/>
			<xs:enumeration value="UsesIVRSTypes"/>
			<xs:enumeration value="PositionRoles"/>
			<xs:enumeration value="ProcessModes"/>
			<xs:enumeration value="AnalysisTypes"/>
			<xs:enumeration value="AnalysisRoles"/>
			<xs:enumeration value="AnalyticComparisonTypes"/>
			<xs:enumeration value="AnalysisSetTypes"/>
			<xs:enumeration value="StudyVariableOrigins"/>
			<xs:enumeration value="StudyDatumStatus"/>
			<xs:enumeration value="InterimAnalysisTypes"/>
			<xs:enumeration value="VariableDataTypes"/>
			<xs:enumeration value="HypothesisTypes"/>
			<xs:enumeration value="TimeIntervalTypes"/>
			<xs:enumeration value="FoodFastingTypes"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Enumerations">
		<xs:union memberTypes="BaseEnumerations xs:string"/>
	</xs:simpleType>
</xs:schema>

=== mfecteau/Mark---Repo/Purdue/1/xmlschema/icd/enmapper.xml
<EnumMapper xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../icd/enmapper.xsd">
  <EnumType enumName="CodedPhaseTypes" enumLabel="CodedPhaseTypes" toolTip="">
    <EnumPair systemName="1" userLabel="phase 1" />
    <EnumPair systemName="1-2" userLabel="phase 1/2" />
    <EnumPair systemName="2" userLabel="phase 2" />
    <EnumPair systemName="2-3" userLabel="phase 2/3" />
    <EnumPair systemName="3" userLabel="phase 3" />
    <EnumPair systemName="3a" userLabel="phase 3a" />
    <EnumPair systemName="3b" userLabel="phase 3b" />
    <EnumPair systemName="4" userLabel="phase 4" />
  </EnumType>
  <EnumType enumName="CurrencyTypes">
    <EnumPair systemName="USDollars" userLabel="US dollars" />
    <EnumPair systemName="UKPounds" userLabel="pounds" />
    <EnumPair systemName="Euros" userLabel="euros" />
    <EnumPair systemName="SwissFrancs" userLabel="Swiss francs" />
    <EnumPair systemName="Yen" userLabel="yen" />
  </EnumType>
  <EnumType enumName="PurposeTypes">
    <EnumPair preserve="true" systemName="Efficacy" userLabel="efficacy" />
    <EnumPair preserve="true" systemName="Safety" userLabel="safety" />
    <EnumPair systemName="Regulatory" userLabel="regulatory" />
    <EnumPair preserve="true" systemName="Screening" userLabel="screening" />
    <EnumPair preserve="true" systemName="Treatment" userLabel="treatment" />
    <EnumPair systemName="StandardOfCare" userLabel="standard of care" />
    <EnumPair systemName="Pharmacokinetic" userLabel="pharmacokinetics" />
    <EnumPair systemName="Pharmacodynamic" userLabel="pharmacodynamics" />
    <EnumPair systemName="Pharmacogenomic" userLabel="pharmacogenomics" />
    <EnumPair systemName="Pharmacoeconomic" userLabel="pharmacoeconomics" />
    <EnumPair systemName="HealthOutcome" userLabel="health outcomes" />
    <EnumPair systemName="QualityofLife" userLabel="quality of life" />
    <EnumPair systemName="other" userLabel="other" />
  </EnumType>
	<EnumType enumName="DGPurposeTypes">  <!-- this is needed by TSD 3.0 -->
    		<EnumPair systemName="Regulatory" userLabel="Other regulatory" />
    		<EnumPair preserve="true" systemName="OtherScreening" userLabel="screening" />
    		<EnumPair preserve="true" systemName="OtherTreatment" userLabel="treatment" />
    		<EnumPair systemName="other" userLabel="other" />
  	</EnumType>
  <EnumType enumName="StudyPurposeTypes">
    <EnumPair systemName="Prevention" userLabel="prevention" />
    <EnumPair preserve="true" systemName="Treatment" userLabel="treatment" />
    <EnumPair systemName="Diagnosis" userLabel="diagnosis" />
    <EnumPair systemName="LongTermSafety" userLabel="long-term safety" />
    <EnumPair systemName="ProofOfConcept" userLabel="proof of concept" />
    <EnumPair systemName="EducCouncilTrain" userLabel="educational/counseling/training" />
    <EnumPair systemName="Conception" userLabel="conception" />
    <EnumPair systemName="other" userLabel="other" />
  </EnumType>
  <EnumType enumName="BlindingTypes">
    <EnumPair systemName="Single-blinded" userLabel="single-blinded" />
    <EnumPair systemName="Double-blinded" userLabel="double-blinded" />
    <EnumPair systemName="Triple-blinded" userLabel="triple-blinded" />
    <EnumPair systemName="Open-label" userLabel="open label" />
    <EnumPair systemName="Third-partyblinded" userLabel="third-party blinded" />
    <EnumPair systemName="other" userLabel="other" />
  </EnumType>
  <EnumType enumName="ControlTypes">
    <EnumPair systemName="Active" userLabel="active-controlled" />
    <EnumPair systemName="Placebo" userLabel="placebo-controlled" />
    <EnumPair systemName="Uncontrolled" userLabel="non-controlled" />
    <EnumPair systemName="Historical" userLabel="retrospectively-controlled" />
    <EnumPair systemName="DoseComparison" userLabel="dose-comparison" />
    <EnumPair systemName="DoubleDummy" userLabel="double-dummy" />
    <EnumPair systemName="ActivePlacebo" userLabel="active-placebo" />
    <EnumPair systemName="other" userLabel="other" />
  </EnumType>
  <EnumType enumName="AllocationTypes">
    <EnumPair systemName="Randomized" userLabel="randomized" />
    <EnumPair systemName="Unrandomized" userLabel="non-randomized" />
    <EnumPair systemName="other" userLabel="other" />
  </EnumType>
  <EnumType enumName="ConfigurationTypes">
    <EnumPair systemName="Parallel" userLabel="parallel-group" />
    <EnumPair systemName="Single-group" userLabel="single-group" />
    <EnumPair systemName="Cross-over" userLabel="cross-over" />
    <EnumPair systemName="Factorial" userLabel="factorial" />
    <EnumPair systemName="Cohort" userLabel="cohort" />
    <EnumPair systemName="titration" userLabel="dose titration" />
    <EnumPair systemName="up-titration" userLabel="up-titration" />
    <EnumPair systemName="down-titration" userLabel="down-titration" />
    <EnumPair systemName="other" userLabel="other" />
  </EnumType>
  <EnumType enumName="OverallStudyOutcomeTypes">
    <EnumPair preserve="true" systemName="Safety" userLabel="safety" />
    <EnumPair preserve="true" systemName="Efficacy" userLabel="efficacy" />
    <EnumPair systemName="Safety-efficacy" userLabel="safety and efficacy" />
    <EnumPair systemName="Bio-equivalence" userLabel="bioequivalence" />
    <EnumPair systemName="Bio-availability" userLabel="bioavailability" />
    <EnumPair systemName="Pharmacokinetics" userLabel="pharmacokinetic" />
    <EnumPair systemName="Pharmacodynamics" userLabel="pharmacodynamic" />
    <EnumPair systemName="PkPd" userLabel="pharmacokinetic/pharmacodynamic" />
    <EnumPair systemName="PopPk" userLabel="population pharmacokinetic" />
    <EnumPair systemName="Pharmacoeconomic" userLabel="pharmacoeconomic" />
    <EnumPair systemName="Pharmacogenomic" userLabel="pharmacogenomic" />
    <EnumPair systemName="QOL" userLabel="quality of life" />
    <EnumPair systemName="HealthEcon" userLabel="health economics" />
    <EnumPair systemName="other" userLabel="other" />
  </EnumType>
  <EnumType enumName="InvestigationTypes">
    <EnumPair systemName="observational" userLabel="observational" />
    <EnumPair systemName="interventional" userLabel="interventional" />
    <EnumPair systemName="other" userLabel="other" />
  </EnumType>
  <EnumType enumName="OutcomeTypes">
    <EnumPair preserve="true" systemName="PrimaryEfficacy" userLabel="primary efficacy" />
    <EnumPair preserve="true" systemName="SecondaryEfficacy" userLabel="secondary efficacy" />
    <EnumPair systemName="TertiaryEfficacy" userLabel="tertiary efficacy" />
    <EnumPair preserve="true" systemName="Safety" userLabel="safety" />
    <EnumPair systemName="Pharmacoeconomic" userLabel="pharmacoeconomic" />
    <EnumPair systemName="Pharmacogenomic" userLabel="pharmacogenomic" />
    <EnumPair systemName="Pharmacodynamic" userLabel="pharmacodynamic" />
    <EnumPair systemName="Pharmacokinetic" userLabel="pharmacokinetic" />
    <EnumPair systemName="Quality of Life" userLabel="quality of life" />
    <EnumPair systemName="Exploratory" userLabel="exploratory" />
    <EnumPair systemName="other" userLabel="other" />
  </EnumType>
  <EnumType enumName="ObjectiveTypes">
    <EnumPair preserve="true" systemName="Primary" userLabel="primary" />
    <EnumPair preserve="true" systemName="Secondary" userLabel="secondary" />
    <EnumPair preserve="true" systemName="Tertiary" userLabel="tertiary" />
    <EnumPair preserve="true" systemName="Safety" userLabel="safety" />
    <EnumPair systemName="other" userLabel="other" />
  </EnumType>
  <EnumType enumName="CTMaterialTypes">
    <EnumPair systemName="Drug" userLabel="drug" />
    <EnumPair systemName="GeneTransfer" userLabel="gene transfer" />
    <EnumPair systemName="Device" userLabel="device" />
    <EnumPair systemName="Vaccine" userLabel="vaccine" />
    <EnumPair systemName="Behavior" userLabel="behavior" />
    <EnumPair systemName="Procedure" userLabel="procedure" />
    <EnumPair systemName="Radiation" userLabel="radiation" />
    <EnumPair systemName="other" userLabel="other" />
  </EnumType>
  <EnumType enumName="RouteOfAdminTypes">
    <EnumPair systemName="Topical" userLabel="topical" />
    <EnumPair systemName="Oral" userLabel="oral" />
    <EnumPair systemName="Intramuscular" userLabel="intramuscular" />
    <EnumPair systemName="Intravenous" userLabel="intravenous" />
    <EnumPair systemName="Subcutaneous" userLabel="subcutaneous" />
    <EnumPair systemName="Sublingual" userLabel="sublingual" />
    <EnumPair systemName="Rectal" userLabel="rectal" />
    <EnumPair systemName="Inhalation" userLabel="inhalation" />
    <EnumPair systemName="Transdermal" userLabel="transdermal" />
    <EnumPair systemName="other" userLabel="other" />
  </EnumType>
  <EnumType enumName="FormulationTypes">
    <EnumPair systemName="Tablet" userLabel="tablet" />
    <EnumPair systemName="Capsule" userLabel="capsule" />
    <EnumPair systemName="Liquid" userLabel="liquid" />
    <EnumPair systemName="Suspension" userLabel="suspension" />
    <EnumPair systemName="Powder" userLabel="powder" />
    <EnumPair systemName="Patch" userLabel="patch" />
    <EnumPair systemName="other" userLabel="other" />
  </EnumType>
  <EnumType enumName="EntranceCriterionTypes">
    <EnumPair preserve="true" systemName="Inclusion" userLabel="inclusion" />
    <EnumPair preserve="true" systemName="Exclusion" userLabel="exclusion" />
    <EnumPair systemName="other" userLabel="other" />
  </EnumType>
  <EnumType enumName="GenderTypes">
    <EnumPair systemName="Male" userLabel="male" />
    <EnumPair systemName="Female" userLabel="female" />
    <EnumPair systemName="Both" userLabel="male and female" />
    <EnumPair systemName="other" userLabel="other" />
  </EnumType>
  <EnumType enumName="AlphaTailTypes">
    <EnumPair systemName="OneTailed" userLabel="one-tailed" />
    <EnumPair systemName="TwoTailed" userLabel="two-tailed" />
    <EnumPair systemName="other" userLabel="other" />
  </EnumType>
